import os
import sys
import getpass

# This script guides the user through the final, simplified one-time setup process.

def get_user_input(prompt):
    """A simple helper to get non-empty input from the user."""
    user_input = ""
    while not user_input:
        user_input = input(prompt).strip()
        if not user_input:
            print("This field cannot be empty.")
    return user_input

def create_env_file():
    """Guides the user and creates the simplified .env file."""
    print("--- Kim Young-mi: Final Setup ---")
    print("I'll guide you through setting me up. I only need three things.\n")

    # --- Gather Information ---
    player_username = get_user_input("1. What is your Valorant username (e.g., YourName)?\n   (This is the name that appears in the kill feed, without the #tagline)\n   > ")
    ollama_model = get_user_input("2. What is the name of the Ollama model you want me to use?\n   (e.g., 'llama2', 'mistral', 'phi')\n   > ")
    pantry_id = get_user_input("3. What is your Pantry ID from getpantry.cloud?\n   > ")

    # --- Create .env File Content ---
    env_content = f"""
# This file was automatically generated by the setup wizard.
OLLAMA_MODEL="{ollama_model}"
PLAYER_USERNAME="{player_username}"
PANTRY_ID="{pantry_id}"
"""

    # --- Write the .env File ---
    try:
        with open(".env", "w") as f:
            f.write(env_content.strip())
        print("\n[SUCCESS] Your .env configuration file has been created!")
        return True
    except Exception as e:
        print(f"\n[ERROR] Could not create the .env file: {e}")
        return False

def create_startup_shortcut():
    """
    Creates a shortcut in the Windows Startup folder to run the app silently.
    """
    print("\n--- Creating Startup Task ---")

    if sys.platform != "win32":
        print("[INFO] This setup step is for Windows only. Skipping startup task creation.")
        return True # On non-Windows, we don't fail, just skip.

    script_dir = os.path.dirname(os.path.abspath(__file__))
    target_path = os.path.join(script_dir, "run_silent.pyw")
    username = getpass.getuser()
    startup_folder = os.path.join(f"C:\\Users\\{username}\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup")
    shortcut_path = os.path.join(startup_folder, "Kim Young-mi AI.lnk")

    print(f"I will create a shortcut here: {shortcut_path}")

    vbs_script_content = f'''
    Set oWS = WScript.CreateObject("WScript.Shell")
    sLinkFile = "{shortcut_path}"
    Set oLink = oWS.CreateShortcut(sLinkFile)
    oLink.TargetPath = "{sys.executable.replace('python.exe', 'pythonw.exe')}"
    oLink.Arguments = "{target_path}"
    oLink.WorkingDirectory = "{script_dir}"
    oLink.WindowStyle = 7
    oLink.Save
    '''

    vbs_path = os.path.join(script_dir, "create_shortcut.vbs")
    try:
        with open(vbs_path, "w") as f:
            f.write(vbs_script_content)
        os.system(f'cscript //nologo "{vbs_path}"')
        print("[SUCCESS] Startup shortcut created successfully.")
        return True
    except Exception as e:
        print(f"[ERROR] Failed to create startup shortcut: {e}")
        return False
    finally:
        if os.path.exists(vbs_path):
            os.remove(vbs_path)

if __name__ == "__main__":
    if create_env_file():
        if create_startup_shortcut():
            print("\n--- All Done! ---")
            print("I am now fully set up and will start silently when you log in.")
            print("You can close this window now. I'll be waiting for you in the game.")
    else:
        print("\nSetup failed. Please check the errors above and try again.")

    input("\nPress Enter to exit.")