import os
import sys
import getpass

# This script guides the user through a one-time setup process,
# creates the .env file, and sets up the application to run on startup.

def get_user_input(prompt, is_path=False):
    """A helper to get non-empty input from the user, with path validation."""
    user_input = ""
    while True:
        user_input = input(prompt).strip()
        if not user_input:
            print("This field cannot be empty.")
            continue
        if is_path and not os.path.exists(user_input):
            print("\nERROR: The file path you provided does not exist.")
            continue
        break
    return user_input

def create_env_file():
    """Guides the user and creates the .env file."""
    print("--- Kim Young-mi: One-Time Setup Wizard ---")
    print("I'll guide you through setting me up. Please provide the following information.")
    print("You can find most of these keys from the service websites.\n")

    # --- Gather Information ---
    player_username = get_user_input("1. What is your Valorant username (e.g., YourName)?\n   (This is the name that appears in the kill feed, without the #tagline)\n   > ")
    openai_key = get_user_input("2. What is your OpenAI API Key?\n   > ")
    serpapi_key = get_user_input("3. What is your SerpApi API Key?\n   > ")
    gcloud_project = get_user_input("4. What is your Google Cloud Project ID?\n   > ")
    gcloud_creds_path = get_user_input("5. What is the full path to your Google Cloud Service Account JSON file?\n   > ", is_path=True)

    # --- Create .env File Content ---
    env_content = f"""
# This file was automatically generated by the setup wizard.
OPENAI_API_KEY="{openai_key}"
SERPAPI_API_KEY="{serpapi_key}"
GCLOUD_PROJECT="{gcloud_project}"
GOOGLE_APPLICATION_CREDENTIALS="{gcloud_creds_path}"
PLAYER_USERNAME="{player_username}"
"""

    # --- Write the .env File ---
    try:
        with open(".env", "w") as f:
            f.write(env_content.strip())
        print("\n[SUCCESS] Your .env configuration file has been created!")
        return True
    except Exception as e:
        print(f"\n[ERROR] Could not create the .env file: {e}")
        return False

def create_startup_shortcut():
    """
    Creates a shortcut in the Windows Startup folder to run the app silently.
    This is done by generating and executing a VBScript, which is a reliable
    method on Windows without requiring extra dependencies.
    """
    print("\n--- Creating Startup Task ---")

    # Check if we are on Windows
    if sys.platform != "win32":
        print("[ERROR] This setup script is designed for Windows only.")
        print("Could not create startup task.")
        return False

    # Get necessary paths
    script_dir = os.path.dirname(os.path.abspath(__file__))
    target_path = os.path.join(script_dir, "run_silent.pyw")
    username = getpass.getuser()
    startup_folder = os.path.join(f"C:\\Users\\{username}\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup")
    shortcut_path = os.path.join(startup_folder, "Kim Young-mi AI.lnk")

    print(f"I will create a shortcut here: {shortcut_path}")

    # VBScript content to create the shortcut
    vbs_script_content = f'''
    Set oWS = WScript.CreateObject("WScript.Shell")
    sLinkFile = "{shortcut_path}"
    Set oLink = oWS.CreateShortcut(sLinkFile)
    oLink.TargetPath = "{sys.executable}"
    oLink.Arguments = "{target_path}"
    oLink.WorkingDirectory = "{script_dir}"
    oLink.WindowStyle = 7
    oLink.Save
    '''

    # Write and execute the VBScript
    vbs_path = os.path.join(script_dir, "create_shortcut.vbs")
    try:
        with open(vbs_path, "w") as f:
            f.write(vbs_script_content)

        # Execute the script using cscript
        os.system(f'cscript //nologo "{vbs_path}"')

        print("[SUCCESS] Startup shortcut created successfully.")
        return True
    except Exception as e:
        print(f"[ERROR] Failed to create startup shortcut: {e}")
        return False
    finally:
        # Clean up the temporary VBScript
        if os.path.exists(vbs_path):
            os.remove(vbs_path)

if __name__ == "__main__":
    if create_env_file():
        if create_startup_shortcut():
            print("\n--- All Done! ---")
            print("I am now fully set up and will start silently when you log in.")
            print("You can close this window now. I'll be waiting for you in the game.")
    else:
        print("\nSetup failed. Please check the errors above and try again.")

    input("\nPress Enter to exit.")